system {
        allow_knet_handle_fallback: yes
}

totem {
        version: 2
        cluster_name: web-cluster
        secauth: false
        crypto_cipher: none
        crypto_hash: none
}

logging {
        fileline: off
        to_stderr: yes
        to_logfile: yes
        logfile: /var/log/corosync/corosync.log
        to_syslog: yes
        debug: off
        logger_subsys {
                subsys: QUORUM
                debug: off
        }
}

quorum {
        provider: corosync_votequorum
}

nodelist {
    node {
        name: node1
        nodeid: 1
        ring0_addr: node1
    }

    node {
        name: node2
        nodeid: 2
        ring0_addr: node2
    }
}